In [1]:
import numpy as np
import urx
import math
from decimal import *
import pandas as pd
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [29]:
# robo = urx.Robot("localhost")
robo = urx.Robot("172.16.101.224")

tried 11 times to find a packet in data, advertised packet size: -2, type: 3
Data length: 68
tried 11 times to find a packet in data, advertised packet size: -2, type: 3
Data length: 1092
tried 11 times to find a packet in data, advertised packet size: -2, type: 3
Data length: 1454
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/robo/.local/lib/python3.6/site-packages/urx/ursecmon.py", line 286, in run
    data = self._get_data()
  File "/home/robo/.local/lib/python3.6/site-packages/urx/ursecmon.py", line 333, in _get_data
    tmp = self._s_secondary.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/robo/.local/lib/python3.6/site-packages/urx/ursecmon.py", line 286, in run
    data = 

In [4]:
#Home position
robo.movej((0, -1.57, 1.57, 0, 1.57, 3.14),0.2,0.2,wait=False)

In [34]:
robo.movej((-3.1, -1.6, 1.6, -1.6, -1.6, 0.0),1,1,wait=False) #input joint values

In [35]:
I = robo.getl()
I

[0.4765157848055126,
 0.15033558730939428,
 0.49071489380414174,
 -2.265589368947053,
 2.174192072540314,
 -0.0648332834714804]

In [53]:
robo.movej((-3.100, -1.105, 0.975, 1.672, 1.600, -3.142),1,1,wait=False) #fastik solution 6

In [54]:
c = robo.getl()
c

[0.47714105804464624,
 0.15036160908980117,
 0.4906779391876316,
 -2.266263303250065,
 2.1739393822273523,
 -0.0643970285905482]

In [55]:
np.array(I) - np.array(c)

array([-0.001, -0.000, 0.000, 0.001, 0.000, -0.000])

In [38]:
robo.movej((-3.100, -1.107, 0.978, 1.671, 1.600, -3.142),1,1,wait=False) #Solur5ik solution 1

In [39]:
a =robo.getl()
a

[0.4764324936135095,
 0.15033212100861706,
 0.49067002782592417,
 -2.2662633032499775,
 2.1739393822274606,
 -0.06439702858998204]

In [46]:
np.array(I) - np.array(a)

array([0.000, 0.000, 0.000, 0.001, 0.000, -0.000])

In [40]:
robo.movej((-3.100, -1.106, 0.976, 1.672, 1.600, -3.140),1,1,wait=False) #Solur5ik solution from ee_pose 1

In [41]:
d =robo.getl()
d

[0.4767615688708326,
 0.15034581601997454,
 0.4908686314288252,
 -2.264058688855107,
 2.176176162662625,
 -0.0643952823096667]

In [47]:
np.array(I) - np.array(d)

array([-0.000, -0.000, -0.000, -0.002, -0.002, -0.000])

In [12]:
robo.set_freedrive(0)

In [ ]:
robo.stop()

In [7]:
#Home position
robo.movej((0, -1.57, 1.57, 0, 1.57, 3.14),0.2,0.2,wait=False)

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/robo/.local/lib/python3.6/site-packages/urx/ursecmon.py", line 286, in run
    data = self._get_data()
  File "/home/robo/.local/lib/python3.6/site-packages/urx/ursecmon.py", line 333, in _get_data
    tmp = self._s_secondary.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer



In [8]:
robo.getl()

[-0.49234175220120224,
 -0.1329010195873261,
 0.487881945991931,
 -1.2099592230237057,
 -1.2092894533655278,
 1.2086744920293737]

In [25]:
plate_reg_Y = robo.getl() 
plate_reg_Y[0:3]

[-0.4732470637264985, -0.46916063788467727, 0.12652691618583747]

In [20]:
# plate_reg_X = robo.getl() 
plate_reg_X[0:3]

[-0.36267705111997617, -0.5583422749208483, 0.12511033451707934]

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/robo/.local/lib/python3.6/site-packages/urx/ursecmon.py", line 286, in run
    data = self._get_data()
  File "/home/robo/.local/lib/python3.6/site-packages/urx/ursecmon.py", line 333, in _get_data
    tmp = self._s_secondary.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/robo/.local/lib/python3.6/site-packages/urx/ursecmon.py", line 286, in run
    data = self._get_data()
  File "/home/robo/.local/lib/python3.6/site-packages/urx/ursecmon.py", line 333, in _get_data
    tmp = self._s_secondary.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer



In [22]:
# plate_reg_O = robo.getl() 
plate_reg_O[:3]

[-0.46212743982551896, -0.5689311288750145, 0.1263949715929509]

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/robo/.local/lib/python3.6/site-packages/urx/ursecmon.py", line 286, in run
    data = self._get_data()
  File "/home/robo/.local/lib/python3.6/site-packages/urx/ursecmon.py", line 333, in _get_data
    tmp = self._s_secondary.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer



In [16]:
o = robo.get_orientation() #after manually aligning z-orientation
o

<Orientation: 
array([[0.031, 0.687, -0.726],
       [0.999, -0.005, 0.038],
       [0.022, -0.726, -0.687]])>

In [25]:
0.164-0.205

-0.04099999999999998

In [31]:
0.16865 -0.1522

0.016449999999999992